[tool.poetry]
name = "git-archiver"
version = "0.1.0"
description = ""
authors = ["Albert Seligmann <ase@ipu.dk>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.8"
python-gitlab = "^3.15.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
